### ISSUE TITLE
NeoJSONReader tendency to create Floats

### ISSUE THREAD

**Issue by 3zork** [svenvc/NeoJSON#15]
I had posted in the VA Smalltalk forum the below.  Mariano suggested I post my question here.
--
Our application deals with money, and therefore we avoid problems with Float, and use ScaledDecimal instead. But NeoJSONReader gives you a Float for instance:

| n1 n2 |
n1 := 1.14s2.
n2 := (NeoJSONReader on: (NeoJSONWriter toString: n1) readStream) next.
n1 - n2

My result is -2.22044604925031e-16

Yes, I could fix this in many of our classes with neoJsonMapping: methods. But wouldn't it be OK to just change #parseNumberFraction, which is the source of the Floats? Simple fix to change '1.0' to '1 asScaledDecimal', and '10.0' to '10' here:

parseNumberFraction
    | number power |
    number := 0.
    power := 1 asScaledDecimal.
    [ readStream atEnd not and: [ readStream peek isDigit ] ]
        whileTrue: [
            number := 10 * number + readStream next digitValue.
            power := power * 10 ].
    ^ number / power

**Comment by svenvc** [comment]
Hi,

I believe this has come up before. Here are some points:

- in the original JSON specification (https://www.json.org/json-en.html) nothing much is being said about numbers. this is probably intentional. in any case, AFAIK, NeoJSON supports this correctly
- yes, all numbers except integers are converted to floats, as this is all the specification allows
- it is not possible to preserve other number types (fractions, scaled decimals, complex numbers) under serialisation/deserialisation as there is no allowed syntax for them
- your suggested fix would turn all float numbers into scaled decimals, which would be unacceptable

You could just subclass NeoJSONReader and overwrite #parseNumberFraction for your particular use case.

Sven

PS: I am not so sure ScaledDecimal is a solution to representing precise money values. There have been many, many discussions about this class over the years. If it were me, I would store the smallest relevant unit (say cents) as an integer and make sure nothing is lost or the correct rounding rules are used during any computation. But this is not easy (divisions, percentages), still I believe these accounting rules do exist.
